name: Streak
on:
  schedule:
    - cron: '23 12 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run commit script
        run: |
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${{ secrets.USER_EMAIL }}"
          git commit --allow-empty -m "Streak grass: $(date +'%Y-%m-%d %H:%M:%S')"
          git push origin main
